# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: printer.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'printer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprinter.proto\x12\x07printer\"\'\n\x08TextTask\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"/\n\x0bTextRequest\x12 \n\x05tasks\x18\x01 \x03(\x0b\x32\x11.printer.TextTask\"\"\n\x0fPrinterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x06Number\x12\x0e\n\x06number\x18\x01 \x01(\x05\"=\n\x05Range\x12\x13\n\x0bstartNumber\x18\x01 \x01(\x05\x12\x11\n\tendNumber\x18\x02 \x01(\x05\x12\x0c\n\x04step\x18\x03 \x01(\x05\x32\xc4\x01\n\x07Printer\x12@\n\x0cPrintStrings\x12\x14.printer.TextRequest\x1a\x18.printer.PrinterResponse0\x01\x12=\n\x0ePrintFibonacci\x12\x0f.printer.Number\x1a\x18.printer.PrinterResponse0\x01\x12\x38\n\nPrintRange\x12\x0e.printer.Range\x1a\x18.printer.PrinterResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'printer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTTASK']._serialized_start=26
  _globals['_TEXTTASK']._serialized_end=65
  _globals['_TEXTREQUEST']._serialized_start=67
  _globals['_TEXTREQUEST']._serialized_end=114
  _globals['_PRINTERRESPONSE']._serialized_start=116
  _globals['_PRINTERRESPONSE']._serialized_end=150
  _globals['_NUMBER']._serialized_start=152
  _globals['_NUMBER']._serialized_end=176
  _globals['_RANGE']._serialized_start=178
  _globals['_RANGE']._serialized_end=239
  _globals['_PRINTER']._serialized_start=242
  _globals['_PRINTER']._serialized_end=438
# @@protoc_insertion_point(module_scope)
