# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import printer_pb2 as printer__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in printer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrinterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrintStrings = channel.unary_stream(
                '/printer.Printer/PrintStrings',
                request_serializer=printer__pb2.TextRequest.SerializeToString,
                response_deserializer=printer__pb2.PrinterResponse.FromString,
                _registered_method=True)
        self.PrintFibonacci = channel.unary_stream(
                '/printer.Printer/PrintFibonacci',
                request_serializer=printer__pb2.Number.SerializeToString,
                response_deserializer=printer__pb2.PrinterResponse.FromString,
                _registered_method=True)
        self.PrintRange = channel.unary_stream(
                '/printer.Printer/PrintRange',
                request_serializer=printer__pb2.Range.SerializeToString,
                response_deserializer=printer__pb2.PrinterResponse.FromString,
                _registered_method=True)


class PrinterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PrintStrings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintFibonacci(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrinterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrintStrings': grpc.unary_stream_rpc_method_handler(
                    servicer.PrintStrings,
                    request_deserializer=printer__pb2.TextRequest.FromString,
                    response_serializer=printer__pb2.PrinterResponse.SerializeToString,
            ),
            'PrintFibonacci': grpc.unary_stream_rpc_method_handler(
                    servicer.PrintFibonacci,
                    request_deserializer=printer__pb2.Number.FromString,
                    response_serializer=printer__pb2.PrinterResponse.SerializeToString,
            ),
            'PrintRange': grpc.unary_stream_rpc_method_handler(
                    servicer.PrintRange,
                    request_deserializer=printer__pb2.Range.FromString,
                    response_serializer=printer__pb2.PrinterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'printer.Printer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('printer.Printer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Printer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrintStrings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/printer.Printer/PrintStrings',
            printer__pb2.TextRequest.SerializeToString,
            printer__pb2.PrinterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrintFibonacci(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/printer.Printer/PrintFibonacci',
            printer__pb2.Number.SerializeToString,
            printer__pb2.PrinterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrintRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/printer.Printer/PrintRange',
            printer__pb2.Range.SerializeToString,
            printer__pb2.PrinterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
